name: shelf_backend
description: A Shelf server wrapping the OpenAI API.
version: 1.0.0

environment:
  sdk: ^3.3.0

dependencies:
  args: ^2.4.0
  http: ^1.2.1
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
